### ISSUE TITLE
Fix toast for authentication page 

### ISSUE THREAD

**Issue by Ehm-Ehs** [PorePranav/CampusUnify#5] opened 2024-10-04 06:42 UTC
<img width="1440" alt="Screenshot 2024-10-04 at 07 41 10" src="https://github.com/user-attachments/assets/5a19fc06-fbdc-45e9-953b-31dbe72f6553">
the toast are not carrying any message

**Comment by PorePranav** [comment] 2024-10-04 07:13
Hi @Ehm-Ehs,
Thanks for opening up the issue. Seems the same issue as #1, can you please provide a bit more information on the issue such as steps to reproduce or logs if any so that I can better understand the problem.

**Comment by namansharma3007** [comment] 2024-10-04 07:51
@Ehm-Ehs Please assign this issue to me I can handle it.

**Comment by namansharma3007** [comment] 2024-10-04 07:53
@Ehm-Ehs I can handle this issue. I have worked with toast. Please, assign this issue to me.

**Comment by PorePranav** [comment] 2024-10-04 12:45
@Ehm-Ehs Another person is already working on the same issue, if they aren't able to come up with a solution, I'll assign it to you! Meanwhile, I will be keeping this issue open. Also, the issue isn't totally related to react-hot-toast.

**Comment by PorePranav** [comment] 2024-10-12 05:58
Issue already fixed by 50885ed668bf043be2d90ab646d49d210c441a12, closing!

**Closed by PorePranav** 2024-10-12 05:58 UTC
